Ajax2
KayumovELdar/ker pull request #7
Opened 2021-04-04 03:19 UTC by KayumovELdar

2021-04-04 09:24 UTC, vkurennov requested changes
Где фича-тесты на голосование? Ты по идее с них должен был начать

2021-04-04 09:24 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +module Voted
а почему этот модуль не включен в контроллер ответов? и если ты это пропустил, то возникает вопрос к тестам - а ты протестировал голосование за ответы?

2021-04-04 09:24 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes.destroy_all if votes.exists?(user: user)
ха, вот тут у тебя очень интересный баг)) ты удаляешь все голоса за объет, если есть голос от переданного юзера. Представь ситуацию: за ответ проголосовало 100 человек, один решил отменить голос и ты удалеешь голоса всех оставшихся 99 юзеров.

Прежде чем писать фикс на этот баг, напиши тест, воспроизовдящий его, т.е. создай голоса от нескольких разных юзеров (не многих, 3 достаточно), удали от одного из них и проверь, что голоса остальных остались. Тест должен упасть. После этого напиши фикс и тест пройдет. Это как раз подход к багфиксам в методоллогии TDD

2021-04-04 09:24 UTC, vkurennov commented on spec/controllers/concerns/voted_spec.rb
> +shared_examples_for 'voted' do
где вызов этой спеки для контроллера ответов?

2021-04-05 01:41 UTC, KayumovELdar reviewed
с трудом я привыкаю к методике TDD, если переводить на инженерный язык, в тестах мы описываем техническое задание в не яном виде, которое и должна выполнить программа, правда, из-за не опытности, написать все сразу пока, что сложновато...

2021-04-05 01:41 UTC, KayumovELdar commented on app/controllers/concerns/voted.rb
> +module Voted
ааа увидел, когда правил некоторые баги последний коммит забыл добавить

2021-04-05 11:08 UTC, vkurennov approved these changes

2021-04-05 11:38 UTC, merged